export const InitialState = {
	files: [],
	currentFile: null,
	fileHighlights: [],
	myPosts: [],
	allPosts: [],
	error: null,
	message: null,
	searchQuery: "",
	isModalOpen: false,
	nodeData: {},
	nodesData: {},
	graphData: {},
	highlightColors: JSON.parse(localStorage.getItem("highlightColors")) || { default: "#F48FB1", legalTest: "#E1BEE7", issue: "#D1C4E9", conclusion: "#B2EBF2" },
	auth: {
		userId: null,
		authToken: null,
		userPublicId: null,
		username: null,
		email: null,
		expiry: null,
		fname: null,
		lname: null,
		city: null,
		country: null,
		organisation: null,
	},
	highlightTextsForEditor: [],

};